
package cn.itcast.ws.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyWebServerService", targetNamespace = "http://server.ws.itcast.cn/", wsdlLocation = "http://localhost:8888/MyWebServer?wsdl")
public class MyWebServerService
    extends Service
{

    private final static URL MYWEBSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYWEBSERVERSERVICE_EXCEPTION;
    private final static QName MYWEBSERVERSERVICE_QNAME = new QName("http://server.ws.itcast.cn/", "MyWebServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/MyWebServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYWEBSERVERSERVICE_WSDL_LOCATION = url;
        MYWEBSERVERSERVICE_EXCEPTION = e;
    }

    public MyWebServerService() {
        super(__getWsdlLocation(), MYWEBSERVERSERVICE_QNAME);
    }

    public MyWebServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYWEBSERVERSERVICE_QNAME, features);
    }

    public MyWebServerService(URL wsdlLocation) {
        super(wsdlLocation, MYWEBSERVERSERVICE_QNAME);
    }

    public MyWebServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYWEBSERVERSERVICE_QNAME, features);
    }

    public MyWebServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyWebServer
     */
    @WebEndpoint(name = "MyWebServerPort")
    public MyWebServer getMyWebServerPort() {
        return super.getPort(new QName("http://server.ws.itcast.cn/", "MyWebServerPort"), MyWebServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebServer
     */
    @WebEndpoint(name = "MyWebServerPort")
    public MyWebServer getMyWebServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.ws.itcast.cn/", "MyWebServerPort"), MyWebServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYWEBSERVERSERVICE_EXCEPTION!= null) {
            throw MYWEBSERVERSERVICE_EXCEPTION;
        }
        return MYWEBSERVERSERVICE_WSDL_LOCATION;
    }

}
